export const STORAGE_KEYS = {
  ACCESS_TOKEN: 'auth_access_token',
  REFRESH_TOKEN: 'auth_refresh_token',
  USER_DATA: 'auth_user_data',
  EXPIRES_AT: 'auth_expires_at',
  SELECTED_ENVIRONMENT: 'selected_environment',
  AUTH_RESET_DONE: 'auth_reset_done_v1',
  ENCRYPTED_CREDENTIALS: 'auth_encrypted_credentials',
  REMEMBER_ME: 'auth_remember_me',
  PIN_HASH: 'auth_pin_hash',
  ONBOARDING_COMPLETED: 'onboarding_completed',
  RECENT_RECIPIENTS: 'recent_recipients',
  FAVORITE_CURRENCIES: 'favorite_currencies',
  HIDE_ZERO_BALANCES: 'hide_zero_balances',
} as const;
